### ISSUE TITLE
Support for PHP 5

### ISSUE THREAD

**Issue by bladeofsteel** [decahedronio/monolog-sticky-context#1]
the lack of support for php 5 is a conscious decision or simply because you not using it?
current monolog support 5.3 but your handler can use only on php 7

**Comment by phroggyy** [comment]
We want to encourage people to use modern versions of PHP. PHP 5.6 was EOL beginning of last year, and currently only gets security updates (until December 2018). Therefore, we are avoiding supporting PHP versions lower than 7.0.

**Comment by bladeofsteel** [comment]
ok, tnx
